// functions/index.js
// Firebase Cloud Function: send certificate email to client
const functions = require('firebase-functions');
const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: functions.config().email.user,
    pass: functions.config().email.password,
  },
});

exports.sendCertificateEmail = functions.https.onCall(async (data, context) => {
  if (!context.auth) {
    throw new functions.https.HttpsError('unauthenticated', 'Must be authenticated');
  }

  const {
    toEmail,
    toName,
    certificateUrl,
    serialNumber,
    overallResult,
    engineerName,
    calibrationDate,
    manufacturer,
    model,
  } = data;

  const resultBadge = overallResult
    ? '✅ CALIBRATION PASSED'
    : '❌ CALIBRATION FAILED';

  const html = `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #f4f6fa;">
      <div style="background: #0D1B2A; padding: 32px 40px; border-radius: 12px 12px 0 0;">
        <h1 style="color: white; margin: 0; font-size: 24px;">Caliborty</h1>
        <p style="color: rgba(255,255,255,0.6); margin: 4px 0 0;">وحدة معايرة واستشارات الأجهزة الطبية</p>
        <p style="color: rgba(255,255,255,0.5); font-size: 12px; margin: 2px 0 0;">Faculty of Engineering · Minia University</p>
      </div>
      
      <div style="background: white; padding: 32px 40px;">
        <p style="font-size: 16px; color: #546E7A;">Dear ${toName},</p>
        
        <p style="color: #0D1B2A; font-size: 16px; line-height: 1.6;">
          Your medical equipment calibration has been completed. Please find the details below:
        </p>
        
        <div style="background: #f4f6fa; border-radius: 12px; padding: 20px; margin: 24px 0;">
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; color: #546E7A; font-size: 14px;">Serial Number:</td>
              <td style="padding: 8px 0; font-weight: 600; color: #0D1B2A;">${serialNumber}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #546E7A; font-size: 14px;">Manufacturer:</td>
              <td style="padding: 8px 0; font-weight: 600; color: #0D1B2A;">${manufacturer}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #546E7A; font-size: 14px;">Model:</td>
              <td style="padding: 8px 0; font-weight: 600; color: #0D1B2A;">${model}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #546E7A; font-size: 14px;">Calibration Date:</td>
              <td style="padding: 8px 0; font-weight: 600; color: #0D1B2A;">${calibrationDate}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #546E7A; font-size: 14px;">Engineer:</td>
              <td style="padding: 8px 0; font-weight: 600; color: #0D1B2A;">${engineerName}</td>
            </tr>
          </table>
        </div>
        
        <div style="text-align: center; padding: 20px; background: ${overallResult ? '#E8F5E9' : '#FFEBEE'}; 
                    border-radius: 12px; margin-bottom: 28px; 
                    border: 1px solid ${overallResult ? '#A5D6A7' : '#EF9A9A'};">
          <span style="font-size: 22px; font-weight: 800; color: ${overallResult ? '#2E7D32' : '#C62828'};">
            ${resultBadge}
          </span>
        </div>
        
        ${certificateUrl ? `
        <div style="text-align: center; margin-bottom: 24px;">
          <a href="${certificateUrl}" 
             style="background: #1565C0; color: white; padding: 14px 32px; 
                    border-radius: 10px; text-decoration: none; 
                    font-weight: 700; font-size: 15px; display: inline-block;">
            📄 Download Certificate
          </a>
        </div>
        ` : ''}
        
        <p style="color: #546E7A; font-size: 13px; line-height: 1.6;">
          This certificate has been generated by UMECC (Unit of Medical Equipment Calibration & Consultation), 
          Faculty of Engineering, Minia University.
        </p>
      </div>
      
      <div style="background: #f4f6fa; padding: 20px 40px; border-radius: 0 0 12px 12px; text-align: center;">
        <p style="color: #90A4AE; font-size: 12px; margin: 0;">
          UMECC · Faculty of Engineering · Minia University<br>
          This is an automated message from Caliborty App
        </p>
      </div>
    </div>
  `;

  const mailOptions = {
    from: `"UMECC - Caliborty" <${functions.config().email.user}>`,
    to: toEmail,
    subject: `📋 Calibration Certificate - ${serialNumber} | ${resultBadge}`,
    html,
  };

  await transporter.sendMail(mailOptions);
  return { success: true };
});
