// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP8FINVFurzEagy8HsA3PqWogb_Prq2yM',
    appId: '1:384729302768:web:7cd191df9b2218234e6435',
    messagingSenderId: '384729302768',
    projectId: 'learn-c2ce0',
    authDomain: 'learn-c2ce0.firebaseapp.com',
    storageBucket: 'learn-c2ce0.appspot.com',
    measurementId: 'G-RPMZ69T8VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY8pcOf8ZdOnWkqIcZG1ygb500B32fI-g',
    appId: '1:384729302768:android:1d1b1cdf431168fd4e6435',
    messagingSenderId: '384729302768',
    projectId: 'learn-c2ce0',
    storageBucket: 'learn-c2ce0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6VjOHCoEZ01q8hp8C46UWrpt-rusFW34',
    appId: '1:384729302768:ios:37784c969eba0c1e4e6435',
    messagingSenderId: '384729302768',
    projectId: 'learn-c2ce0',
    storageBucket: 'learn-c2ce0.appspot.com',
    iosClientId: '384729302768-s10vr0p1rrcrnehmf39td0mdm9e33c5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.calibratory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6VjOHCoEZ01q8hp8C46UWrpt-rusFW34',
    appId: '1:384729302768:ios:37784c969eba0c1e4e6435',
    messagingSenderId: '384729302768',
    projectId: 'learn-c2ce0',
    storageBucket: 'learn-c2ce0.appspot.com',
    iosClientId: '384729302768-s10vr0p1rrcrnehmf39td0mdm9e33c5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.calibratory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlVwfo2MYWmv_N3zMCPvyo1zbWyV6PKec',
    appId: '1:384729302768:web:698132e51f1848bd4e6435',
    messagingSenderId: '384729302768',
    projectId: 'learn-c2ce0',
    authDomain: 'learn-c2ce0.firebaseapp.com',
    storageBucket: 'learn-c2ce0.appspot.com',
    measurementId: 'G-SZ1G9TB0PD',
  );
}
