// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHmsShZ9eTBIbFj2JC5FRW2LFyxutopZ4',
    appId: '1:879929112778:web:3a05d04b6a7d8ed78e9c33',
    messagingSenderId: '879929112778',
    projectId: 'ourapp-7b3f5',
    authDomain: 'ourapp-7b3f5.firebaseapp.com',
    storageBucket: 'ourapp-7b3f5.appspot.com',
    measurementId: 'G-1R0S2TB2E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6dVu2XwwQoddnlcvPLHJOGGWJLoUfQeM',
    appId: '1:879929112778:android:0f35e31cbb6905c68e9c33',
    messagingSenderId: '879929112778',
    projectId: 'ourapp-7b3f5',
    storageBucket: 'ourapp-7b3f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyzdsWLwGvRFXbG1-AUY1bgDW3kYgLpZg',
    appId: '1:879929112778:ios:01c271dd27e39f418e9c33',
    messagingSenderId: '879929112778',
    projectId: 'ourapp-7b3f5',
    storageBucket: 'ourapp-7b3f5.appspot.com',
    androidClientId: '879929112778-adaq7b3tibuncksfhiru03aop15b58bt.apps.googleusercontent.com',
    iosClientId: '879929112778-3c35d4e5n9d5to7slg4jarje0hauva4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.calibratory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyzdsWLwGvRFXbG1-AUY1bgDW3kYgLpZg',
    appId: '1:879929112778:ios:01c271dd27e39f418e9c33',
    messagingSenderId: '879929112778',
    projectId: 'ourapp-7b3f5',
    storageBucket: 'ourapp-7b3f5.appspot.com',
    androidClientId: '879929112778-adaq7b3tibuncksfhiru03aop15b58bt.apps.googleusercontent.com',
    iosClientId: '879929112778-3c35d4e5n9d5to7slg4jarje0hauva4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.calibratory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3eLB8IsgmO1L0b8zlUm4TkYuSBKFDTxU',
    appId: '1:879929112778:web:2af81b6cca9e997a8e9c33',
    messagingSenderId: '879929112778',
    projectId: 'ourapp-7b3f5',
    authDomain: 'ourapp-7b3f5.firebaseapp.com',
    storageBucket: 'ourapp-7b3f5.appspot.com',
    measurementId: 'G-WJZGNGG58K',
  );

}